### ISSUE TITLE
Joiner crashes immediately

### ISSUE THREAD

**Issue by chaarlottte** [YABOIpy/GoDm#13]
```
2023/04/18 16:06:33 Get "https://discord.com": read tcp 10.24.18.213:52319->91.239.130.17:40000: wsarecv: An existing connection was forcibly closed by the remote host.
2023/04/18 16:06:33 Get "https://discord.com": read tcp 10.24.18.213:52319->91.239.130.17:40000: wsarecv: An existing connection was forcibly closed by the remote host.
exit status 1
```
Basically always get an error similar to this right after the tokens stop connecting to the websocket, and it immediately crashes. You could implement some sort of try/catch function to stop this.

**Comment by YABOIpy** [comment]
Porxy issue. And it does iterate after getting an error but ill look into it might be bacuse of log.fatal most likely

**Comment by chaarlottte** [comment]
Happens without proxies as well, however I’ve noticed that without proxies it often crashes before printing anything out.

**Comment by YABOIpy** [comment]
Thats due to the same reason updates later
