### ISSUE TITLE
flagged joiner

### ISSUE THREAD

**Issue by malsaddAS** [YABOIpy/GoDm#17]
joiner is now flagged
i am using uhq tokens and proxies

**Comment by YABOIpy** [comment]
Show a screenshot..

**Comment by malsaddAS** [comment]
> Show a screenshot..

https://xvrt-is-in.allah.agency/4u6j2i8i.png

**Comment by malsaddAS** [comment]
there uhq tokens
brand new fv and proxies.gg

**Comment by YABOIpy** [comment]
Ill look at it later when i have time

**Comment by YABOIpy** [comment]
simple fix ill add in the next update

<img width="281" alt="image" src="https://user-images.githubusercontent.com/110062350/235253981-af71e9d9-adb2-40d2-bc81-5030a323cd20.png">

**Comment by YABOIpy** [comment]
was a mistake from my side i updated the cookie function but forgot to implement it
silly.. 😅
