### ISSUE TITLE
Can't join server

### ISSUE THREAD

**Issue by zpo2miedzyrzec** [YABOIpy/GoDm#21]
2023/08/30 09:15:13 websocket: close 4004: Authentication failed.
panic: runtime error: invalid memory address or nil pointer dereference
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7efdce]

goroutine 27 [running]:
github.com/gorilla/websocket.(*Conn).Close(0x0?)
    /home/yukoo/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:345 +0xe
panic({0x86c5c0?, 0xcf8160?})
    /snap/go/10319/src/runtime/panic.go:914 +0x21f
main.LoadChoice.func4.1({{{0x8f1280, 0x5}, {0x8f2dfc, 0x9}, {0x8f2480, 0x8}, {0xc000175340, 0x69}, {0x8f0a91, 0x2}}, ...})
    /home/yukoo/GoDm/main.go:102 +0xda
source/src/task.StartTask.func1(_, {{{0x8f1280, 0x5}, {0x8f2dfc, 0x9}, {0x8f2480, 0x8}, {0xc000175340, 0x69}, {0x8f0a91, ...}}, ...})
    /home/yukoo/GoDm/src/task/task.go:37 +0x95
created by source/src/task.StartTask in goroutine 1
    /home/yukoo/GoDm/src/task/task.go:35 +0x147
exit status 2

**Comment by YABOIpy** [comment]
I have to add error handling to the websockets. I have yet to do this. Maybe in the future

**Comment by zpo2miedzyrzec** [comment]
so how can i fix this

**Comment by YABOIpy** [comment]
By fixing the error handling inside websockets.go

**Comment by zpo2miedzyrzec** [comment]
i wont do it cuz i dont understand anything but thank you anyways

**Comment by zpo2miedzyrzec** [comment]
can this probblem be with my internet? I installed this on vmware and it shows the same error
