### ISSUE TITLE
I'm having trouble running GoDM, it just stopped out of nowhere.

### ISSUE THREAD

**Issue by UmJapah** [YABOIpy/GoDm#23]
I'm having trouble running GoDM, it just stopped out of nowhere.

C:\Users\GoDM>go run main.go
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
source/src/modules.BuildInfo()
        C:\Users\GoDM/src/modules/modules.go:368 +0x77a
source/src/modules.init()
        C:\Users\GoDM
![Captura de tela 2023-09-04 160126](https://github.com/YABOIpy/GoDm/assets/104688660/550e6bfa-0a19-4115-a537-37c2134a07ba)
/src/modules/types.go:80 +0x13
exit status 2

**Comment by YABOIpy** [comment]
You have already asked me this i gave an answer.
