### ISSUE TITLE
error running 

### ISSUE THREAD

**Issue by UmJapah** [YABOIpy/GoDm#26]
There is an error when running the bot, it has some errors

**Comment by UmJapah** [comment]
[3.0ms] [X]Failed: <!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>

**Comment by YABOIpy** [comment]
Read the readme on how to make issues. This error is most likely caused by a rate limit

**Comment by YABOIpy** [comment]
Well never mind discord got blocked by cloudlfare 🤣😆😆

**Comment by UmJapah** [comment]
All tokens are falling lol it's complicated here 🤣🤣🤣
