### ISSUE TITLE
Joiner isnt working

### ISSUE THREAD

**Issue by Mosaibh** [YABOIpy/GoDm#36]
Its either i dont know how to use it properly or its not working well. Do you mind explaining me how to use it properly?

**Comment by YABOIpy** [comment]
Read readme. If it doesnt work then it doesnt work

**Comment by Mosaibh** [comment]
why does it keep saying ignored whenever i tried

**Comment by YABOIpy** [comment]
No captcha support. It says it in the readme that it is yet to be added.

**Comment by YABOIpy** [comment]
fingerprint was flagged. update the config. ive updated it should work fine now. if not your tokens are flagged
