### ISSUE TITLE
Booster Not Working

### ISSUE THREAD

**Issue by 981726** [YABOIpy/GoDm#40]
2024/10/10 13:11:45 invalid character 'e' looking for beginning of value
[94.ms] [X][MTIwNDI1Mjg1NTc1NDgyMTY3Mg] Failed To Boost: 1285029368816472155
Going Back To Menu =>..

error ^

Account's valid, Has Nitro In the Server Aswell. Replcaed Exe Reinstalled Everything Nothing

**Comment by YABOIpy** [comment]
Wait till Update possibly outdated function
